spring:
  datasource:
    url: jdbc:mysql://localhost:3307/pill_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 150MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

file:
  upload-dir: /Users/chlwjd/All_Project/pill/images/
  sample-dir: /Users/chlwjd/All_Project/pill/samples/

#  image, samples ???? ???? ???? ??